---@type LazySpec
return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.pack.lua" },
  { import = "astrocommunity.recipes.disable-tabline" },
  { import = "astrocommunity.completion.blink-cmp" },
  { import = "astrocommunity.editing-support.conform-nvim" },
  { import = "astrocommunity.pack.typescript" },
  { import = "astrocommunity.icon.mini-icons" },
  { import = "astrocommunity.motion.leap-nvim" },
  { import = "astrocommunity.pack.python" },
  { import = "astrocommunity.diagnostics.trouble-nvim" },
  { import = "astrocommunity.completion.avante-nvim" },
  { import = "astrocommunity.completion.copilot-lua-cmp" },
  { import = "astrocommunity.colorscheme.catppuccin" },
  { import = "astrocommunity.recipes.vscode" },
  { import = "astrocommunity.pack.go" },
  { import = "astrocommunity.pack.prisma" },
  { import = "astrocommunity.pack.tailwindcss" },
}
